name: "nested-actions-spike"

runs:
  using: "composite"
  steps:
    - id: context
      shell: bash
      run: echo '${{ toJSON(github.action_path) }}'
    - uses: actions/github-script@v6
      with:
        script: |
          console.log(process.env)
