name: "we-can-name this anything we want?"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/github-script@v6
      id: "just-testing-this"
      with:
        script: |
          const script = require('./script.js')
          console.log(await script())
    - uses: actions/github-script@v6
      with:
        script: |
          console.log(process.env)
