name: "nested-actions-spike"

runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v6
      with:
        script: |
          console.log(process.env)
    - uses: actions/github-script@v6
      with:
        script: |
          console.log(${{ toJSON(github.action_repository) }})
