name: "nested-actions-spike-something"

runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v6
      with:
        script: |
          console.log(process.env)
    - uses: actions/github-script@v6
      with:
        script: |
          const actionName = ${{ toJSON(github.action) }}
          const [repoOrg, repoName] = actionName.split('_')
          console.log(repoOrg)
          console.log(repoName)
        # this could be the key!
