name: "nested-actions-spike"

runs:
  using: "composite"
  steps:
    - run: echo '${{ toJSON(github) }}'
    - uses: actions/github-script@v6
      with:
        script: |
          console.log(process.env)
