name: "nested-actions-spike"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/github-script@v6
      with:
        script: |
          console.log(process.env)
          const script require('./script.js')
          console.log(script())
